---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-todo-app
  namespace: todo-app  # Fixed indentation (2 spaces)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-todo
  template:
    metadata:
      labels:
        app: php-todo
    spec:
      containers:
      - name: php-todo
        image: admin335/php-todo-app:v1.0-25
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: ""  # Consider using a Kubernetes Secret instead
        - name: DB_NAME
          value: todo_app
---
apiVersion: v1
kind: Service
metadata:
  name: php-todo-service
  namespace: todo-app  # Added namespace for consistency
spec:
  type: NodePort
  selector:
    app: php-todo
  ports:
  - port: 80
    targetPort: 80
